/* Demo content for the Ethio Telecom pitch.
 *
 * PRODUCT.md § Evidence on Hand: there are no real users, videos or metrics,
 * and none may be fabricated as real. Everything below is authored demo
 * material, produced at full fidelity because a pitch has to look like the
 * product — and marked on screen wherever it could be mistaken for live
 * data. Creator names are generic first names with a masked phone, so no
 * real person is represented.
 *
 * The seed mirrors PLAN.md's brief (2 demo subscribers, 3 demo videos) and
 * goes past it, because a three-card rack cannot show what a rack is.
 */

import type { Category, Subscriber, Video } from './types'

const DAY = 86_400_000
const now = Date.now()
const ago = (days: number, hours = 0) =>
  new Date(now - days * DAY - hours * 3_600_000).toISOString()

/** The two credentialed demo accounts. Password for both: `talent123`.
 *  Surfaced on the login screen behind a demo marker so the room can log in. */
export const DEMO_LOGIN = { phone: '0911223344', password: 'talent123' }

export const subscribers: Subscriber[] = [
  { id: 1, phone_number: '0911223344', display_name: 'ሰላም ተ.', status: 'active', created_on: ago(96) },
  { id: 2, phone_number: '0922334455', display_name: 'ዳዊት ም.', status: 'active', created_on: ago(74) },
  { id: 3, phone_number: '0913778823', display_name: 'ሄለን ግ.', status: 'active', created_on: ago(61) },
  { id: 4, phone_number: '0947213392', display_name: 'ብሩክ አ.', status: 'active', created_on: ago(52) },
  { id: 5, phone_number: '0935618065', display_name: 'ማርታ ደ.', status: 'active', created_on: ago(33) },
  { id: 6, phone_number: '0918442214', display_name: 'ዮሐንስ ከ.', status: 'active', created_on: ago(19) },
]

interface Seed {
  id: number
  by: number
  title: string
  category: Category
  views: number
  days: number
  dur: number
}

const seed: Seed[] = [
  { id: 1, by: 6, title: 'የእናቴ ዘፈን — በክራር', category: 'instrument', views: 41, days: 0, dur: 94 },
  { id: 2, by: 3, title: 'እስክስታ በአራት ኪሎ', category: 'dance', views: 218, days: 1, dur: 62 },
  { id: 3, by: 2, title: 'ስለ ታክሲ ወያላዎች', category: 'comedy', views: 1174, days: 2, dur: 118 },
  { id: 4, by: 5, title: 'ግጥም፦ አዲስ አበባ ጠዋት', category: 'poetry', views: 96, days: 4, dur: 71 },
  { id: 5, by: 1, title: 'ማሲንቆ ብቻውን', category: 'instrument', views: 507, days: 6, dur: 143 },
  { id: 6, by: 4, title: 'የሠርግ ዘፈን — ጎንደር', category: 'song', views: 2390, days: 9, dur: 86 },
  { id: 7, by: 2, title: 'ኮሜዲ፦ የቤት ኪራይ ወግ', category: 'comedy', views: 843, days: 13, dur: 105 },
  { id: 8, by: 3, title: 'ትዝታ በአዲስ ድምፅ', category: 'song', views: 1682, days: 18, dur: 132 },
  { id: 9, by: 5, title: 'የጉራጌ ዳንስ — ቡድን', category: 'dance', views: 604, days: 24, dur: 79 },
  { id: 10, by: 1, title: 'የልጅነት ትዝታ — ግጥም', category: 'poetry', views: 149, days: 31, dur: 58 },
  { id: 11, by: 6, title: 'ዋሽንት በሸዋ ቅኝት', category: 'instrument', views: 388, days: 40, dur: 121 },
  { id: 12, by: 4, title: 'የመድረክ ቀልድ — ክፍል ፩', category: 'comedy', views: 2951, days: 55, dur: 164 },
]

export const videos: Video[] = seed.map((s) => ({
  id: s.id,
  subscriber_id: s.by,
  title: s.title,
  /* Generated by `npm run demo:media`. Absent until then; the player shows
     its labelled demo state rather than a broken element. */
  video_path: `/demo/clip-${((s.id - 1) % 5) + 1}.mp4`,
  thumbnail_path: null, // prints are generated client-side from the seed
  view_count: s.views,
  status: 'approved',
  posted_on: ago(s.days, (s.id * 3) % 24),
  category: s.category,
  duration_s: s.dur,
}))
